apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: opentelemetry-operator-system 
spec:
  python:
    # Auto-instrumentation package for Python
    image: ghcr.io/open-telemetry/opentelemetry-operator-autoinstrumentation-python:latest
    env:
      - name: OTEL_SERVICE_NAME
        value: "my-python-app"
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector:4317"
      - name: OTEL_EXPORTER_JAEGER_ENDPOINT
        value: "http://jaeger:14250"  # Update with the correct Jaeger endpoint if needed
