apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: opentelemetry-operator-system
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:  # Batching the traces and metrics for efficient processing
    exporters:
      # Jaeger Exporter (for trace visualization in Jaeger)
      jaeger:
        endpoint: "http://jaeger-collector:14250"
        insecure: true

      # Prometheus Exporter (for metrics visualization in Prometheus)
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "opentelemetry-operator-system"
        send_timestamps: true

      # Tempo Exporter (for trace storage in Grafana Tempo)
      otlp/tempo:
        endpoint: "tempo:4317"
        insecure: true

      # Logging Exporter (for debugging purposes)
      logging:
        logLevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, otlp/tempo, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]
